<template>
TÉCNICOS DENTRO DO SISTEMA <br></br>
ATUALIZAR O CADASTRO DE DATA DE NASCIMENTO (O NASCIMENTO PODE OCORRER POSTERIOR Á hoje)<br></br>
FAZER DASHBOARDS <br></br>
PENSAR EM NOVAS FUNCIONALIDADES<br></br>
CUSTO DE UMA TAREFA<br></br>
PROFISSIONAL DA TAREFA<br></br>
SETOR<BR></BR>
PRIORIDADE<BR></BR>

</template>

<script setup>

</script>