FROM golang:1.25

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    PATH="/go/bin:$PATH"

WORKDIR /backend

COPY backend/go.mod backend/go.sum ./

RUN go mod download

COPY backend/ .

RUN go build -o /go/bin/main ./cmd

EXPOSE 8090

CMD ["/go/bin/main"]