FROM golang:1.25

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    PATH="/go/bin:$PATH"

WORKDIR /backend

RUN go install github.com/air-verse/air@latest

COPY backend/go.mod ./
RUN go mod download

COPY backend/ .

EXPOSE 8090

CMD ["air", "-c", ".air.toml"]