# .air.toml
[build]
  cmd = "go build -o main ."
  bin = "main"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["vendor", "node_modules"]
  exclude_file = []
  follow_symlink = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
